### ISSUE TITLE
cmake: Individual functional tests cannot be run

### ISSUE THREAD

**Issue by achow101** [hebasto/bitcoin#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Running an individual functional test directly is not possible as the files do not exist in the out of tree build. For example, trying to run `test/functional/wallet_basic.py` from the build dir is not possible.

### Expected behaviour

It should be possible to run all functional tests directly. Furthermore, these should be symlinked as making changes to the test in the source directory should result in the executed test also changing without needing a rebuild.

### Steps to reproduce

Build normally. Run a functional test by providing the relative path to it as if you were in the root of the source directory.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

c1e196794c35837b1819b6706c5d909587af1feb

### Operating system and version

Arch

**Comment by hebasto** [comment]
Please see https://github.com/hebasto/bitcoin/pull/226.
