### ISSUE TITLE
Implement enable-external-warnings

### ISSUE THREAD

**Issue by fanquake** [hebasto/bitcoin#223]
There is demand for this feature to continue to exist, i.e https://github.com/bitcoin/bitcoin/pull/30189#issuecomment-2137467259, so we should have the ability to do a CMake build, exposing all external warnings, from dependencies etc.

**Comment by hebasto** [comment]
This can be done by `-DCMAKE_NO_SYSTEM_FROM_IMPORTED=ON`.

**Comment by fanquake** [comment]
> It only spits out a few boost (and other dependencies) warnings

Isn't that the point though? (Potential) bugs in upstream code are likely represented as warnings emitted by the compiler, and the way to find those early is to see the warnings when dependencies change. In any case, did some minor tests with `DCMAKE_NO_SYSTEM_FROM_IMPORTED`, and it should work.
