### ISSUE TITLE
Bad practice to set rule variables?

### ISSUE THREAD

**Issue by real-or-random** [hebasto/bitcoin#239]
https://github.com/hebasto/bitcoin/blob/4778d2800e4883d27812499cfa5354bb0cdaa620/CMakeLists.txt#L168-L174

(added in https://github.com/hebasto/bitcoin/commit/84b83b3c2d393a1f914807300b88963e77444224)

https://cmake.org/pipermail/cmake/2011-September/046090.html says that we are not supposed to set rule variables such as `CMAKE_CXX_COMPILE_OBJECT`, or, if we really need to, set use [CMAKE_USER_MAKE_RULES_OVERRIDE](https://cmake.org/cmake/help/latest/variable/CMAKE_USER_MAKE_RULES_OVERRIDE.html).

Is this code block supposed to achieve the same as our `SECP256K1_LATE_CFLAGS`  (implemented by a user-defined function `all_targets_add_compile_options`) in libsecp256k1?

**Comment by hebasto** [comment]
> Is this code block supposed to achieve the same as our `SECP256K1_LATE_CFLAGS` (implemented by a user-defined function `all_targets_add_compile_options`) in libsecp256k1?

It is. But this approach guaranties to override even options that are abstracted by CMake, for instance https://github.com/hebasto/bitcoin/pull/157#issuecomment-2090465123.

**Comment by real-or-random** [comment]
Okay, sorry, I wasn't aware of the history of this. I agree that #240 is not better.

Perhaps it's a good idea to add a comment above the `string(APPEND` instructions that explains these considerations.
For example:
```
Overriding rule variables such as those below is discouraged, but it's the only way to guarantee that the contents of the APPEND_*FLAGS variables appear at the end of the command line.
```

We could also add something like "This is a global override intended for debugging and special builds." to the descriptions of the variables.


--- 

For consistency with libsecp256k1:

> > Is this code block supposed to achieve the same as our `SECP256K1_LATE_CFLAGS` (implemented by a user-defined function `all_targets_add_compile_options`) in libsecp256k1?
> 
> It is. But this approach guaranties to override even options that are abstracted by CMake, for instance [#157 (comment)](https://github.com/hebasto/bitcoin/pull/157#issuecomment-2090465123).

 - If we agree that appending to rule variables is superior, should we also do this in libsecp256k1?
 - And/or should we rename the `SECP256K1_LATE_CFLAGS` variable to `APPEND_CFLAGS`?

**Comment by hebasto** [comment]
> For consistency with libsecp256k1:
> 
> > > Is this code block supposed to achieve the same as our `SECP256K1_LATE_CFLAGS` (implemented by a user-defined function `all_targets_add_compile_options`) in libsecp256k1?
> > 
> > 
> > It is. But this approach guaranties to override even options that are abstracted by CMake, for instance [#157 (comment)](https://github.com/hebasto/bitcoin/pull/157#issuecomment-2090465123).
> 
>    * If we agree that appending to rule variables is superior, should we also do this in libsecp256k1?
> 
>    * And/or should we rename the `SECP256K1_LATE_CFLAGS` variable to `APPEND_CFLAGS`?

That was/is the plan :)

(after setting everything in Bitcoin Core)

**Comment by hebasto** [comment]
> Perhaps it's a good idea to add a comment above the `string(APPEND` instructions that explains these considerations. For example:
> 
> ```
> Overriding rule variables such as those below is discouraged, but it's the only way to guarantee that the contents of the APPEND_*FLAGS variables appear at the end of the command line.
> ```

I agree to add an explanatory comment, but considering this technique as discouraged basing on a post that predates CMake 3.0, seems a bit exaggerated.

**Comment by real-or-random** [comment]
> I agree to add an explanatory comment, but considering this technique as discouraged basing on a post that predates CMake 3.0, seems a bit exaggerated.

Agreed. 

```
Appending to these low-level rule variables is the only way to guarantee that the flags appear at the end of the command line.
```

**Comment by hebasto** [comment]
See https://github.com/bitcoin-core/secp256k1/pull/1546.

**Comment by hebasto** [comment]
@real-or-random 

Can this issue be closed or I missed something and left it unaddressed?

**Comment by hebasto** [comment]
> See [bitcoin-core/secp256k1#1546](https://github.com/bitcoin-core/secp256k1/pull/1546).

Did this merged PR resolve this issue?

**Comment by hebasto** [comment]
> Strictly speaking, no, due to what I said in the previous comment: ;)
> 
> > It's a nit anyway, but perhaps change the description and add the comment also in this repo for consistency. I guess these things will diverge at some point because they live in different repos, but we could at least try to keep it consistent.

Sure. See https://github.com/hebasto/bitcoin/pull/244.
