### ISSUE TITLE
Missing handling for OBJCXXFLAGS ?

### ISSUE THREAD

**Issue by fanquake** [hebasto/bitcoin#260]
We have code for deplicating/handling `CMAKE_C_FLAGS`/`CMAKE_CXX_FLAGS`/`CMAKE_EXE_LINKER_FLAGS`, but I can't see it for `OBJCXXFLAGS`? Is this not needed, or just missing?

Note that on master we also have `OBJCXXFLAGS="$CXXFLAGS -Wno-deprecated-declarations"` for silencing deprecations (in our own code), but don't see the equivalent in CMake?

**Comment by hebasto** [comment]
> We have code for deplicating/handling `CMAKE_C_FLAGS`/`CMAKE_CXX_FLAGS`/`CMAKE_EXE_LINKER_FLAGS`, but I can't see it for `OBJCXXFLAGS`? Is this not needed, or just missing?

The current `depends/toolchain.cmake.in` assumes that Objective C++ flags coincide with C++ flags: https://github.com/hebasto/bitcoin/blob/d58a3c02883eafa5b2a09afae2b8db9bc14f4dbf/depends/toolchain.cmake.in#L59-L70

> Note that on master we also have `OBJCXXFLAGS="$CXXFLAGS -Wno-deprecated-declarations"` for silencing deprecations (in our own code), but don't see the equivalent in CMake?

No silencing deprecation is required because the Qt dependency libraries are included as system ones using the `-isystem` flag.

**Comment by fanquake** [comment]
> No silencing deprecation is required because the Qt dependency libraries are included as system ones using the -isystem flag.

Not sure what you mean. It's our code using the deprecated functions, not Qt.

**Comment by hebasto** [comment]
> Note that on master we also have `OBJCXXFLAGS="$CXXFLAGS -Wno-deprecated-declarations"` for silencing deprecations (in our own code), but don't see the equivalent in CMake?

https://github.com/hebasto/bitcoin/blob/d58a3c02883eafa5b2a09afae2b8db9bc14f4dbf/src/qt/CMakeLists.txt#L124-L127



> > No silencing deprecation is required because the Qt dependency libraries are included as system ones using the -isystem flag.
> 
> Not sure what you mean. It's our code using the deprecated functions, not Qt.

You're right. Please ignore my wrong statement in previous https://github.com/hebasto/bitcoin/issues/260#issuecomment-2222656737.

**Comment by fanquake** [comment]
Also, is `OBJC_OLD_DISPATCH_PROTOTYPES` missing, or just missing from the configure output?

**Comment by hebasto** [comment]
> Also, is `OBJC_OLD_DISPATCH_PROTOTYPES` missing, or just missing from the configure output?

Fixed in https://github.com/hebasto/bitcoin/pull/265.

**Comment by fanquake** [comment]
I think this is fixed now.
