### ISSUE TITLE
cmake: -logsourcelocations file name differences

### ISSUE THREAD

**Issue by maflcko** [hebasto/bitcoin#297]
Is this intentional?

autotools:
* Linux: `[init] [wallet/init.cpp:129] [Construct] Wallet disabled! `
* macos: `[init] [wallet/init.cpp:129] [Construct] Wallet disabled! `
* Win: `[init] [D:\a\bitcoin-core-with-ci\bitcoin-core-with-ci\src\wallet\init.cpp:129] [Construct] Wallet disabled! `

Cmake:
* Linux: `[init] [/home/runner/work/_temp/src/wallet/init.cpp:129] [Construct] Wallet disabled! `
* macos: `[init] [/Users/runner/work/bitcoin-core-with-ci/bitcoin-core-with-ci/src/wallet/init.cpp:129] [Construct] Wallet disabled! `
* Win: `[init] [D:\a\bitcoin-core-with-ci\bitcoin-core-with-ci\src\wallet\init.cpp:129] [Construct] Wallet disabled! `

**Comment by fanquake** [comment]
Looks like that is also introducing a source of non-determinism (for non-guix build binaries)?

**Comment by fanquake** [comment]
Seems our usage in configure (when using ccache) just wasn't ported over.

**Comment by hebasto** [comment]
Thanks!

Fixed in https://github.com/hebasto/bitcoin/pull/298.

**Comment by hebasto** [comment]
> Please re-open.

Re-opened.

**Comment by hebasto** [comment]
> > Note: I haven't tried guix. Those are the CI-generated binaries. I'll try guix next week, but I expect the result to be the same.
> 
> Testing now, but it still fails. Please re-open.

Fixed in https://github.com/hebasto/bitcoin/pull/315.
