### ISSUE TITLE
Give more useful error when build dir wasn't specified

### ISSUE THREAD

**Issue by paplorinc** [hebasto/bitcoin#306]
I forgot to specify the build dir for cmake (i.e. `cmake -DBUILD_BENCH=ON` instead of `cmake -B build -DBUILD_BENCH=ON`) and got the following error
```
CMake Error at test/CMakeLists.txt:46 (file):
  file CREATE_LINK cannot use same file and newfile
```
[see full log here](https://github.com/user-attachments/files/16510956/scratch_60.txt)

If you think it makes sense, could we display a more useful error when build dir isn't specified?
If it doesn't, feel free to close it without explanation.

**Comment by hebasto** [comment]
> I forgot to specify the build dir for cmake (i.e. `cmake -DBUILD_BENCH=ON` instead of `cmake -B build -DBUILD_BENCH=ON`) ...

This is equivalent to `cmake -B . -DBUILD_BENCH=ON`, which means an in-source build. Although this practice is discouraged by CMake, during an offline discussion with other developers, we decided to leave the user the freedom to choose in-source builds. With https://github.com/hebasto/bitcoin/pull/309, `cmake -DBUILD_BENCH=ON` won't fail with the error mentioned in the original https://github.com/hebasto/bitcoin/issues/306#issue-2451001537.

**Comment by paplorinc** [comment]
Thank you for considering, I'll review that shortly
