### ISSUE TITLE
[RFC] cmake: Consider "None" build type as documented and legitimate to use

### ISSUE THREAD

**Issue by hebasto** [hebasto/bitcoin#92]
It is a follow up related to the discussion in https://github.com/hebasto/bitcoin/pull/82.

Please consider the cashed variables output with help displayed:
```
$ cat CMakeLists.txt 
cmake_minimum_required(VERSION 3.16)
project(test)
$ cmake -B build -LH | grep -A 1 None
// Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=
```

**Comment by hebasto** [comment]
cc @TheCharlatan @theuni @fanquake @m3dwards @dergoegge

**Comment by m3dwards** [comment]
Not much mention of "None" in the docs (https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#default-and-custom-configurations). That section talks about the default being an empty string.

**Comment by hebasto** [comment]
> Not much mention of "None" in the docs (https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#default-and-custom-configurations). That section talks about the default being an empty string.

To be pedantic:
> The default value will _often_ be none of the above standard configurations and will instead be an empty string.

However, my point is about a _non-empty_ value, which does nothing. That is required to override the current code in https://github.com/hebasto/bitcoin/blob/4a7b9fccc6bc8483863a45bf7a246820a3f6a7c5/CMakeLists.txt#L264

**Comment by pablomartin4btc** [comment]
So, as my understanding after discussing it in our last call, in summary:
- Our Default `CMAKE_BUILD_TYPE` is `RelWithDebInfo`.
- Default `CMAKE_BUILD_TYPE` is an empty string.
- Using `-DCMAKE_BUILD_TYPE=None` would make it more explicit when we don't want to set a particular type or leave it to the `CMAKE`s default which doesn't seem appropriate as detailed in `CMAKE`'s [documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html).

**Comment by fanquake** [comment]
Is there anything left to do here?

**Comment by hebasto** [comment]
After a discussion offline with @fanquake, I've verified using the "None" build configuration with a multi-config generator:
```
$ cmake -B build -G "Ninja Multi-Config" -DCMAKE_CONFIGURATION_TYPES="RelWithDebInfo;None"
$ cmake --build build --config None
```
As expected, the build uses the "None" subdirectories in the build tree with no drawbacks.

**Comment by hebasto** [comment]
Closing.

Feel free to open a new issue if any concerns remain.
